import { describe, expect, it } from "vitest";
import { normalizeWalletSignals } from "../services/polymarket/signal-normalizer.ts";

describe("polymarket signal normalizer", () => {
  it("emits new, increased, reduced, and closed position signals", () => {
    const current = new Date("2026-04-01T12:00:00Z");
    const previousPositions = [
      {
        proxyWallet: "0xabc",
        asset: "asset-1",
        conditionId: "market-1",
        size: 10,
        avgPrice: 0.4,
        initialValue: 4,
        currentValue: 5,
        cashPnl: 1,
        percentPnl: 25,
        totalBought: 4,
        realizedPnl: 0,
        percentRealizedPnl: 0,
        curPrice: 0.5,
        title: "Market 1",
        slug: "market-1",
        icon: "",
        eventId: "1",
        eventSlug: "market-1",
        outcome: "Yes",
        outcomeIndex: 0,
        oppositeOutcome: "No",
        oppositeAsset: "asset-1b",
        endDate: current.toISOString(),
        negativeRisk: false,
        latestTradeAt: current,
        spread: null,
      },
      {
        proxyWallet: "0xabc",
        asset: "asset-2",
        conditionId: "market-2",
        size: 10,
        avgPrice: 0.4,
        initialValue: 4,
        currentValue: 5,
        cashPnl: 1,
        percentPnl: 25,
        totalBought: 4,
        realizedPnl: 0,
        percentRealizedPnl: 0,
        curPrice: 0.5,
        title: "Market 2",
        slug: "market-2",
        icon: "",
        eventId: "2",
        eventSlug: "market-2",
        outcome: "Yes",
        outcomeIndex: 0,
        oppositeOutcome: "No",
        oppositeAsset: "asset-2b",
        endDate: current.toISOString(),
        negativeRisk: false,
        latestTradeAt: current,
        spread: null,
      },
      {
        proxyWallet: "0xabc",
        asset: "asset-4",
        conditionId: "market-4",
        size: 8,
        avgPrice: 0.45,
        initialValue: 3.6,
        currentValue: 4,
        cashPnl: 0.4,
        percentPnl: 10,
        totalBought: 3.6,
        realizedPnl: 0,
        percentRealizedPnl: 0,
        curPrice: 0.5,
        title: "Market 4",
        slug: "market-4",
        icon: "",
        eventId: "4",
        eventSlug: "market-4",
        outcome: "Yes",
        outcomeIndex: 0,
        oppositeOutcome: "No",
        oppositeAsset: "asset-4b",
        endDate: current.toISOString(),
        negativeRisk: false,
        latestTradeAt: current,
        spread: null,
      },
    ];
    const currentPositions = [
      { ...previousPositions[0], size: 15, currentValue: 8 },
      {
        ...previousPositions[1],
        asset: "asset-3",
        conditionId: "market-3",
        size: 6,
        title: "Market 3",
        slug: "market-3",
        eventSlug: "market-3",
      },
      {
        ...previousPositions[1],
        asset: "asset-2",
        conditionId: "market-2",
        size: 2,
        currentValue: 1,
      },
    ];

    const signals = normalizeWalletSignals({
      previousPositions,
      currentPositions,
      cadence: "5m",
    });

    expect(signals.map((signal) => signal.action).sort()).toEqual([
      "closed_position",
      "increased_position",
      "new_position",
      "reduced_position",
    ]);
  });
});
